input:
    ground_truths:
        - ../data/static/lo-res/bricks/ground-truth/small-00026.png
        - ../data/static/lo-res/bricks/ground-truth/small-00028.png
    images:
        - ../data/static/lo-res/bricks/images/small-00026.png
        - ../data/static/lo-res/bricks/images/small-00028.png
