preprocess:
    - name: grayscale
      description: grayscalify
      method: to_grayscale

#    - name: hsv
#      desc: hsvify

#    - name: patchify
#      desc: subsample/patchify
#      parameters:
#          - (100, 200)
#          - (200, 200)

features:
    - name: gabor
      description: gabor filter bank
      method: gabor_filter
      parameters:
          - [0.1, 0.2, 0.3, 0.4, 0.5]       # parameter: "spatial_frequencies"
          - [0, 45, 90, 135]                # parameter: "angles"

    - name: glcm
      description: gray-level co-occurrence matrix
      method: glcm
      parameters:
          - [[5]]                           # parameter: "dists"
          - [[0]]                           # parameter: "angles"

#   - lbp:
#        name: local binary patterns
#        parameters:
#            - "{{ blergs }}"
#            - "{{ blargs }}"
#            - "{{ blimey }}"

# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error

## the input data, with associated ground truth.
#input:
#    my_dataset:
#        ground_truth: /path/to/my_dataset/ground_truth
#        data: /path/to/my_dataset/data
