preprocess:
    - name: grayscale
      description: grayscalify
      method: to_grayscale

#    - name: hsv
#      desc: hsvify

#    - name: patchify
#      desc: subsample/patchify
#      parameters:
#          - (100, 200)
#          - (200, 200)

features:
    - name: gabor
      description: gabor filter bank
      method: gabor_filter
      parameters:
          - [0.1, 0.2, 0.3, 0.4, 0.5]       # parameter: "spatial_frequencies"
          - [0, 45, 90, 135]                # parameter: "angles"

# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error
    - name: variance_difference
      method: variance_difference

sort:
    keys:
        - mean_squared_error
        - variance_difference
