preprocess:
    - name: grayscale
      description: grayscalify
      method: to_grayscale

#    - name: hsv
#      desc: hsvify

    - name: patchify
      description: subsample/patchify
      method: to_patches
      parameters:
          - [100]  # parameter: "patch_size"

features:
    - name: glcm
      description: gray-level co-occurrence matrix
      method: glcm
      parameters:
          - [[1], [1, 2], [1, 2, 3, 4, 5]]      # parameter: "dists"
          - [[0, 90, 180, 270]]                 # parameter: "angles"

# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error
    - name: variance_difference
      method: variance_difference

sort:
    keys:
        - mean_squared_error
        - variance_difference
