preprocess: {}
#    - name: hsv
#      desc: hsvify

#    - name: patchify
#      desc: subsample/patchify
#      parameters:
#          - (100, 200)
#          - (200, 200)

features:
    - name: haralick
      description: haralick features
      method: haralick

# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error
    - name: variance_difference
      method: variance_difference

sort:
    keys:
        - mean_squared_error
        - variance_difference
