preprocess:
    - name: grayscale
      description: grayscalify
      method: to_grayscale

#    - name: hsv
#      desc: hsvify

#    - name: patchify
#      desc: subsample/patchify
#      parameters:
#          - (100, 200)
#          - (200, 200)

features:
    - name: lbp
      description: local binary patterns
      method: lbp
      parameters:
          - [1, 3, 5, 8]                    # parameter: "num_points"
          - [8, 24, 40, 100]                # parameter: "radius"
          - ["default"]                     # parameter: "method"

    - name: lbp
      description: rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [1, 3, 5, 8]                    # parameter: "num_points"
          - [8, 24, 40, 100]                # parameter: "radius"
          - ["ror"]                         # parameter: "method"

    - name: lbp
      description: uniform, rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [1, 3, 5, 8]                    # parameter: "num_points"
          - [8, 24, 40, 100]                # parameter: "radius"
          - ["uniform"]                     # parameter: "method"

    - name: lbp
      description: uniform, non-rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [1, 3, 5, 8]                    # parameter: "num_points"
          - [8, 24, 40, 100]                # parameter: "radius"
          - ["nri_uniform"]                 # parameter: "method"


# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error
    - name: variance_difference
      method: variance_difference

# the input data, with associated ground truth.
input:
    ground_truths:
        - ../data/bricks-1/data/bricks-1-no-shadow-1.png
    images:
        - ../data/bricks-1/data/bricks-1-shadow-2.png
