preprocess:
    - name: grayscale
      description: grayscalify
      method: to_grayscale

#    - name: hsv
#      desc: hsvify

#    - name: patchify
#      desc: subsample/patchify
#      parameters:
#          - (100, 200)
#          - (200, 200)

features:
    - name: lbp
      description: local binary patterns
      method: lbp
      parameters:
          - [12, 20, 24]                    # parameter: "num_points"
          - [1, 2, 3, 4, 5]                 # parameter: "radius"
          - ["default"]                     # parameter: "method"

    - name: lbp
      description: rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [12, 20, 24]                    # parameter: "num_points"
          - [1, 2, 3, 4, 5]                 # parameter: "radius"
          - ["ror"]                         # parameter: "method"

    - name: lbp
      description: uniform, rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [12, 20, 24]                    # parameter: "num_points"
          - [1, 2, 3, 4, 5]                 # parameter: "radius"
          - ["uniform"]                     # parameter: "method"

    - name: lbp
      description: uniform, non-rotation-invariant local binary patterns
      method: lbp
      parameters:
          - [12, 20, 24]                    # parameter: "num_points"
          - [1, 2, 3, 4, 5]                 # parameter: "radius"
          - ["nri_uniform"]                 # parameter: "method"


# this defines the statistical tests used to evaluate each technique
tests:
    - name: mean_squared_error
      method: mean_squared_error
    - name: variance_difference
      method: variance_difference

sort:
    keys:
        - mean_squared_error
        - variance_difference
