# preprocessing stages for input images
preprocess:
    - name: grayscale
      description: "converts the image to greyscale"
      method: to_grayscale

    - name: gaussian
      description: "applies a gaussian blur kernel to the image"
      method: gaussian
      parameters:
          - [2]         # blur radius

    - name: local_max
      description: "takes the local maxima over a specified neighbourhood"
      method: local_max
      parameters:
          - [3]         # neighbourhood


# feature extraction
features:
    - name: lbp
      description: "local binary patterns"
      method: lbp
      parameters:
          - [15]        # number of points to sample
          - [5]         # radius
          - ["uniform"] # method


# feature clustering
cluster:
    - name: kmeans
      description: "k-means clustering"
      method: cluster_to_labels
      parameters:
          - [8]         # n_clusters


# where the magic happens
shadow:
    - name: colour
      description: "using variance and otsu thresholds to segment shadow"
      method: variance_otsu


# the tests used to evaluate each technique
metrics:
    - name: binary_classification
      description: "true positives"
      method: true_positives

    - name: binary_classification
      description: "true negatives"
      method: true_negatives

    - name: binary_classification
      description: "false positives"
      method: false_positives

    - name: binary_classification
      description: "false negatives"
      method: false_negatives


# sort results
sort:
    keys:
        - true_positive_rate
        - true_negative_rate
